### ISSUE TITLE
autoprefixer-rails doesn't work with sprockets 3.x in Rails development environment

### ISSUE THREAD

**Issue by edariedl** [ai/autoprefixer-rails#102]
Hi, autoprefixer-rails does not process css during request in development envirenomnt. It worked with Sprockets `2.x` until last night when we upgraded Sprockets to `3.x`.

To be sure it is not issue with our application I've created new Rails 5 application with few controllers according to http://guides.rubyonrails.org/getting_started.html and added `autoprefixer-rails` gem.

My example `scss` code:

```scss
.form-row__inner {
  display: block;
  display: flex;
  align-items: baseline;
}
```

This was generated during request.

```css
.form-row__inner {
    display: block;
    display: flex;
    align-items: baseline;
}
```

Autoprefixer was not executed.

But `rake assets:precompile` works and creates prefixes in css file:

```css
.form-row__inner {
  display: block;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-align: baseline;
      -ms-flex-align: baseline;
          align-items: baseline;
}
```
