### ISSUE TITLE
Is there way to exclude specific prefix?

### ISSUE THREAD

**Issue by jurrick** [ai/autoprefixer-rails#113]
Hi!

Is there way to exclude specific prefix in settings?

For example, I have:

```css
:fullscreen a {
    display: flex
}
```

And autoprefixer generates following:

```css
:-webkit-full-screen a {
    display: -webkit-box;
    display: flex
}
:-moz-full-screen a {
    display: flex
}
:-ms-fullscreen a {
    display: -ms-flexbox;
    display: flex
}
:fullscreen a {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex
}
```

And I want exclude prefix `-ms-flexbox` for `display`.

How can I do it? Which is better way for it?
