### ISSUE TITLE
AP changes gradient values

### ISSUE THREAD

**Issue by glupo** [ai/autoprefixer-rails#131]
Autoprefixing the following css results in changing visual appearance of gradient
**input**
``` css
.select2-container .select2-choice {
    background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, #eee), color-stop(0.5, #fff));
    background-image: -webkit-linear-gradient(center bottom, #eee 0%, #fff 50%);
    background-image: linear-gradient(top, #fff 0%, #eee 50%);
}
```
**output**
``` css
.select2-container .select2-choice {
    background-image: -webkit-gradient(linear, left top, left bottom, from(#fff), color-stop(50%, #eee));
    background-image: linear-gradient(top, #fff 0%, #eee 50%);
}
```
As can be seen in [this fiddle](https://jsfiddle.net/fxxxrpha) the results are different
Same results with default rails workflow and when prefixing using `AutoprefixerRails.process(css)`
