### ISSUE TITLE
No output in Rails 4 app

### ISSUE THREAD

**Issue by hanno-jonlay** [ai/autoprefixer-rails#18]
Hello - I've a little problem.

The Gem seems to be installed okay, but there's no effect on the compiled Sass. I'm wondering if I'm missing something obvious?

Here's my output from `bundle exec rake autoprefixer:inspect`

```
Browsers:
  Android: 4.1, 2.3
  Chrome: 30, 29
  Firefox: 25, 24, 17
  IE: 11, 10, 9, 8
  iOS: 7, 6.1
  Safari: 7, 6.1, 6, 5.1
  Opera: 17, 16, 12.1

Properties:
  @keyframes: webkit
  align-content: -webkit- 2009, webkit, moz, ms
  align-items: -webkit- 2009, webkit, moz, ms
  align-self: -webkit- 2009, webkit, moz, ms
  animation: webkit
  animation-delay: webkit
  animation-direction: webkit
  animation-duration: webkit
  animation-fill-mode: webkit
  animation-iteration-count: webkit
  animation-name: webkit
  animation-play-state: webkit
  animation-timing-function: webkit
  backface-visibility: webkit, ms
  background-clip: webkit
  background-origin: webkit
  background-size: webkit
  border-image: webkit, o
  transition: webkit
  transition-property: webkit
  box-shadow*: webkit
  box-sizing: webkit, moz
  break-after: webkit, moz
  break-before: webkit, moz
  break-inside: webkit, moz
  column-count: webkit, moz
  column-fill: webkit, moz
  column-gap*: webkit, moz
  column-rule*: webkit, moz
  column-rule-color*: webkit, moz
  column-rule-style: webkit, moz
  column-rule-width*: webkit, moz
  column-span: webkit, moz
  column-width*: webkit, moz
  columns*: webkit, moz
  display-flex: -webkit- 2009, webkit, moz, ms
  filter*: webkit
  flex*: -webkit- 2009, webkit, moz, ms
  flex-basis*: -webkit- 2009, webkit, moz, ms
  flex-direction: -webkit- 2009, webkit, moz, ms
  flex-flow: -webkit- 2009, webkit, moz, ms
  flex-grow*: -webkit- 2009, webkit, moz, ms
  flex-shrink*: -webkit- 2009, webkit, moz, ms
  flex-wrap: -webkit- 2009, webkit, moz, ms
  font-feature-settings: webkit, moz
  font-kerning: webkit, moz
  font-language-override: webkit, moz
  font-variant-ligatures: webkit, moz
  hyphens: webkit, moz, ms
  justify-content: -webkit- 2009, webkit, moz, ms
  order: -webkit- 2009, webkit, moz, ms
  perspective*: webkit, ms
  perspective-origin*: webkit, ms
  tab-size: moz, o
  transform*: webkit, ms
  transform-origin*: webkit, ms
  transform-style: webkit, ms
  transition-delay: webkit
  transition-duration: webkit
  transition-timing-function: webkit
  user-select: webkit, moz, ms
  * - can be used in transition

Values:
  linear-gradient: -webkit- old, webkit
  radial-gradient: -webkit- old, webkit
  repeating-linear-gradient: -webkit- old, webkit
  repeating-radial-gradient: -webkit- old, webkit
  calc: webkit
  fill-available: webkit, moz
  fit-content: webkit, moz
  max-content: webkit, moz
  min-content: webkit, moz
  grab: webkit, moz
  grabbing: webkit, moz
  zoom-in: webkit, moz
  zoom-out: webkit, moz
```

It's a Rails 4 app configured for Heroku. I don't know if there are there likely to be any problems with the following Gemfile contents:

```
gem "compass-rails", "~> 1.1.2"
gem 'sass-rails',   '~> 4.0.1'
gem "autoprefixer-rails"
```

A quick test Sass rule, which isn't being processed in any way in the output CSS:

```
.testme {
  transition: transform 1s
}
```

Seems very odd - I'm getting no output whatsoever. Any pointers?
