### ISSUE TITLE
AP skips -moz prefix for gradients

### ISSUE THREAD

**Issue by rwz** [ai/autoprefixer-rails#6]
The setup is Rails 4, sass 3.2.10 and autoprefixer-rails 0.7.20130824

Here's my sass:

``` sass
.landing-page--nav > li > a
  background-color: #e5e5e5
  background-repeat: repeat-x
  background-image: linear-gradient(top, #f5f5f5 0%, #e5e5e5 100%)
```

Here's the compiled CSS:

``` css
.landing-page--nav > li > a {
  background-color: #e5e5e5;
  background-repeat: repeat-x;
  background-image: -webkit-linear-gradient(top, whitesmoke 0%, #e5e5e5 100%);
  background-image: linear-gradient(top, whitesmoke 0%, #e5e5e5 100%);
}
```

Here's how it looks in pretty much any webkit browser: 
![screen shot 2013-09-01 at 20 47 23](https://f.cloud.github.com/assets/129043/1064091/766aba00-130d-11e3-90a6-404264432972.png)

And here's how it looks like in FF 23.0.1:
![screen shot 2013-09-01 at 20 50 52](https://f.cloud.github.com/assets/129043/1064092/8c78a2e4-130d-11e3-9d53-2eb14d52685a.png)

As you can see, there's no gradient.

Expected behavior would be to generate some kind of -moz compatible gradient, or translate W3C gradient into format Firefox could chew up
